[package]
name = "my_multiversx_contract"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"

[dependencies]
elrond-wasm = "0.24" # Example version; check for the latest